name: prayer_app
description: "تطبيق مواقيت الصلاة والأذكار"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

  # --- الحزم الأساسية للمشروع ---
  cupertino_icons: any
  vibration: any
  intl: any
  geolocator: any
  http: any
  shared_preferences: any
  connectivity_plus: any
  flutter_compass: any
  app_settings: any
  audioplayers: ^6.5.0
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  rxdart: ^0.28.0
  permission_handler: ^12.0.0+1
  flutter_background_service: ^5.1.0
  
  android_alarm_manager_plus: ^4.0.7
  flutter_background_service_android: ^6.3.0
  flutter_local_notifications: ^19.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  # --- تعريف الأصول (Assets) ---
  assets:
    - assets/
    - assets/azkar_data.json
    - assets/quran.json
    - assets/Names_Of_Allah.json
    - assets/questions.json
    

  # --- تعريف الخطوط ---
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        
    - family: Uthmani
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
